print("O resultado é ",((2 + 3)-(5 * 8)/4))                           
print("O resultado é ",((7 ** 2) * (4 / 2)))                          
print("O resultado é ", 5 % 5)                                        
print("O resultado é ",(81 ** 0.5))                                   
print("O resultado é ", 0 > 11 and 11 < 12                   )        
print("O resultado é ",(10 * 9) == (20 + 50 * 1 + 20)       )         
print("O resultado é ",(7 == ( 2 * 3.5) and (False or True)))         
print("O resultado é ",(7 > 2 or (7 == (2 ** 2)))           )         
print("O resultado é ",(7 == (2 * 3.5) and (False or True)) )         
print("O resultado é ",(17 / 2) % 2                         )         
print("O resultado é ", not (8 < 16) or (not (18 < 6)))               
print("O resultado é ",(3 < 5) or (3 > 10) and (3 % 2 == 0) )         
print("O resultado é ",(14 != 3) and (3 != 2) or (14 == 0)  )         